name: check-api-changes
description: Check for breaking changes in the public React Native JS API
inputs:
  snapshot-path:
    default: 'packages/react-native/ReactNativeApi.d.ts'
    description: Path to the current snapshot file
runs:
  using: composite
  steps:
    - name: Fetch snapshot from PR head
      shell: bash
      run: |
        mkdir ${{ runner.temp }}/snapshot
        git fetch origin ${{ github.event.pull_request.head.sha }}
        git show ${{ github.event.pull_request.head.sha }}:packages/react-native/ReactNativeApi.d.ts > ${{ runner.temp }}/snapshot/ReactNativeApi.d.ts
    - name: Debug snapshot
      shell: bash
      run: |
        ls -l ${{ runner.temp }}/current-snapshot.d.ts
        cat ${{ runner.temp }}/current-snapshot.d.ts
    # - name: Save previous snapshot
    #   shell: bash
    #   run: |
    #     mkdir ${{ runner.temp }}/snapshot
    #     git show HEAD^:${{ inputs.snapshot-path }} > ${{ runner.temp }}/snapshot/ReactNativeApi.d.ts
    - name: Run breaking change detection
      shell: bash
      run: |
        node ./scripts/diff-api-snapshot \
        ${{ github.workspace }}/${{ inputs.snapshot-path }} \
        ${{ runner.temp }}/snapshot/ReactNativeApi.d.ts \
        > ${{ runner.temp }}/snapshot/output.json
