name: check-api-changes
description: Check for breaking changes in the public React Native JS API
inputs:
  snapshot-path:
    default: 'packages/react-native/ReactNativeApi.d.ts'
    description: Path to the current snapshot file
runs:
  using: composite
  steps:
    - name: Save previous snapshot
      shell: bash
      run: |
        mkdir ${{ runner.temp }}/snapshot
        # git show HEAD^:${{ inputs.snapshot-path }} > ${{ runner.temp }}/snapshot/ReactNativeApi.d.ts
        echo "" > ${{ runner.temp }}/snapshot/ReactNativeApi.d.ts
    - name: Run breaking change detection
      shell: bash
      run: |
        node ./scripts/diff-api-snapshot \
        ${{ runner.temp }}/snapshot/ReactNativeApi.d.ts \
        ${{ github.workspace }}/${{ inputs.snapshot-path }} \
        > ${{ runner.temp }}/snapshot/output.json
